### PR TITLE
Postgres Integration

### LINKED ISSUE #12: Integrate go backend with postgreSQL

### PR DESCRIPTION
**Pull request by williamtdr**
Sets up the two routes to save and retrieve information from a postgres database, using gorm and pq. Resolves #12.

- Assumes a database is running on the local system with the configuration outlined in `main.go`.
- Table structure will be automatically set up on first launch.
- Extends the get endpoint to fetch an entry from the database (this doesn't say anything about output from the honey client yet).
- ScreenShot and Ticket are linked (has a relationship, one per Ticket). Joined across IDs.
- The ID field automatically increments as new tickets are created.

Example runs:
```
~ curl -X POST localhost:8080/api/honeyclient/create -d '{"url": "https://github.com", "name": "github.com", "screenshot": {"width": 1920, "height": 1080, "filename": "screenshot.png"}}'
{"success":true,"message":"Create ticket 'github.com' with ID '2' and URL 'https://github.com'"}

~ curl -X POST localhost:8080/api/honeyclient/create -d '{"url": "http://www.koalastothemax.com", "name": "koalastothemax.com", "screenshot": {"width": 1333, "height": 768, "filename": "screenshot.png"}}'
{"success":true,"message":"Create ticket 'koalastothemax.com' with ID '4' and URL 'http://www.koalastothemax.com'"}

~ curl localhost:8080/api/honeyclient/9
{"success":true,"ticket":{"ID":9,"CreatedAt":"2019-10-22T23:40:03.183188-05:00","UpdatedAt":"2019-10-22T23:40:03.183188-05:00","DeletedAt":null,"name":"github.com","url":"https://github.com","screenshot":{"ID":2,"CreatedAt":"2019-10-22T23:40:03.184276-05:00","UpdatedAt":"2019-10-22T23:40:03.184276-05:00","DeletedAt":null,"TicketID":9,"width":1920,"height":1080,"filename":"screenshot.png"}}}
```

```
gorm=# \dt
           List of relations
 Schema |     Name     | Type  | Owner 
--------+--------------+-------+-------
 public | screen_shots | table | gorm
 public | tickets      | table | gorm
(2 rows)

gorm=# TABLE tickets;
 id |          created_at           |          updated_at           | deleted_at |        name        |              url              
----+-------------------------------+-------------------------------+------------+--------------------+-------------------------------
  9 | 2019-10-22 23:40:03.183188-05 | 2019-10-22 23:40:03.183188-05 |            | github.com         | https://github.com
 10 | 2019-10-22 23:40:06.962091-05 | 2019-10-22 23:40:06.962091-05 |            | koalastothemax.com | http://www.koalastothemax.com
(2 rows)

gorm=# TABLE screen_shots;
 id |          created_at           |          updated_at           | deleted_at | width | height |    filename    | ticket_id 
----+-------------------------------+-------------------------------+------------+-------+--------+----------------+-----------
  2 | 2019-10-22 23:40:03.184276-05 | 2019-10-22 23:40:03.184276-05 |            |  1920 |   1080 | screenshot.png |         9
  3 | 2019-10-22 23:40:06.962457-05 | 2019-10-22 23:40:06.962457-05 |            |  1333 |    768 | screenshot.png |        10
(2 rows)

gorm=# 

```

### CODE REVIEW

**Review by jin-yng — APPROVED** [review]
Looks good! Really like the feel of gorm with this. 

Kool site!

**Comment by rafibarash** [comment]
Just got the database up and running, and for some reason the file artifacts are being created when running the honeyclient but no screenshots are being created? is this happening on your end @williamtdr?

**Comment by williamtdr** [comment]
The screenshots are stored in the table instead of on disk - with the latest versions of the two branches, they aren’t stored on disk at all.

**Comment by rafibarash** [comment]
I mean in the actual Table the screenshots aren't popping up. Here are screenshots of the three tables after I made a ticket request and ran the honeyclient

Here's the ticket table
tickets table

Here's the file_artifacts table
file_artifacts table

Here's the screen_shots table (it is empty)
screen_shots table

Any idea why the screen_shots table is empty for me while the other tables are working as expected?

**Comment by rafibarash** [comment]
realized this is a bug with the honeyclient not the API. Will approve!

**Comment by williamtdr** [comment]
If the screenshots aren't being stored, then the honey client shouldn't be generating anything - as it reads from there.

Please don't remove the screenshot field, it won't be part of the schema otherwise and the HC definitely won't work. We need to preload it to return to the client on the get endpoint.

Can you post the JSON you're using against the create endpoint?

**Comment by rafibarash** [comment]
The screenshots already aren't being processed by the honeyclient, and removing the field doesn't mess up the HC at all
Screen Shot 2019-10-28 at 1 26 29 PM

Also, I believe we don't need to preload the ScreenShot field once we remove the link. The honeyclient is working as expected with the removal of the preload call. 

We're currently only taking the full page screenshot, and for the MVP isn't that what we wanted? Do we really need custom screenshots at the moment? I feel like it would be best to merge this to master so we can start working from the master branch again, and add functionality for additional screenshots later

**Comment by rafibarash** [comment]
There are some kinks to work out after this PR, but necessary to get this code into the master branch

**Pull request merged**
