### PR TITLE
Attempt to add automated testing #38

### PR DESCRIPTION
**Pull request by rafibarash**
Just followed the default workflow suggested by github

### CODE REVIEW

**Comment by rafibarash** [comment]
Well hey looks like this works! It's failing on a test that checks an existing local database connection.

On that note, we should think of some solution that lets us test at least a portion of our code on PRs. One solution is we could mock out the database for any test interacting with it. We could also differentiate unit tests from integration tests and only run unit tests on PRs

What do y'all think?

**Comment by uiryuu** [comment]
Can we actually run a database on the CI server?

**Comment by rafibarash** [comment]
Don't know if we can do that with github actions. It is normally good practice to mock out database calls for all unit tests, and just test the functionality of the service independent of other services.

There is a way to test this with docker using docker-compose, and it should be pretty easy to set up a database along with the tests. This seems like a better solution for integration tests though

**Comment by williamtdr** [comment]
Agreed on the best practice to be mocking. [golang/mock](https://github.com/golang/mock) is nice for this. Alternatively, we could set gORM up with an in-memory database. When it auto migrates the schema, it will set up the in-memory copy, and destroy things when it shuts down.

**Comment by rafibarash** [comment]
@williamtdr @alejx How do you guys feel about submitting this as is (since building the project is still a better check than nothing), and if we can edit this workflow to test the project as well if we decide to mock the tests

**Review by jin-yng — APPROVED** [review]
Just update db creds to gorm.

**Pull request merged**
